[project]
name = "storypark-scraper"
version = "0.0.0"
requires-python = "^3.13"

[virtualenvs]
in-project = true

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
requests = "^2.32.4"
scrapy = "^2.13.3"
